# Generated by Django 4.0.3 on 2022-03-31 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('create_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.TextField(max_length=255)),
                ('profile_picture', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
